In [1]:
import numpy as np
import torch

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [3]:
# Set the random seed so things are predictable
torch.random.manual_seed(42)
# Create random tensor
mat1= torch.rand((6,5))
mat2= torch.rand((1,5))
# Perform matrix multiplication 
mat2=torch.transpose(mat2, 0, 1)
result=torch.mm(mat1, mat2)

print(result)

tensor([[1.9389],
        [1.8879],
        [2.2856],
        [1.3511],
        [1.0735],
        [0.7813]])


2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [26]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [5]:
# Find max
print("Max_Value", torch.max(result))

# Find min
print("Min_Value", torch.min(result))

# Find arg max
print("Max_Arg", torch.argmax(result))

# Find arg min
print("Min_Arg", torch.argmin(result))

Max_Value tensor(2.2856)
Min_Value tensor(0.7813)
Max_Arg tensor(2)
Min_Arg tensor(5)


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [7]:
# Initialize the random seed
torch.manual_seed(7)

# Generate a tensor with random values
tensor1= torch.rand((1,1,1,25))
# Eliminate singleton dimensions
tensor2= torch.squeeze(tensor1)
# Display the tensors along with their shapes
print(tensor2, tensor2.shape)

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513, 0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204, 0.0731,
        0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948, 0.5209]) torch.Size([25])


5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [13]:
tensor1=torch.arange(5)
print(tensor1)
tensor2=torch.reshape(tensor1, (1,5))
print(tensor2)

tensor([0, 1, 2, 3, 4])
tensor([[0, 1, 2, 3, 4]])


6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [18]:
tensor3=torch.randn((2,3))
print(tensor3)
tensor4=torch.add(tensor3,1)
print(tensor4)

tensor([[ 1.0260,  0.6073, -1.6128],
        [-0.0443,  0.2187, -0.0672]])
tensor([[ 2.0260,  1.6073, -0.6128],
        [ 0.9557,  1.2187,  0.9328]])


7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [19]:
tensor5=torch.randn((4,4))
print(tensor5)
tensor6=tensor5[0]
print(tensor6)
tensor7=tensor5[:,-1]
print(tensor7)

tensor([[-0.9578,  1.7518,  0.9796,  0.4105],
        [ 1.7675, -0.0832,  0.5087,  1.1178],
        [ 0.1633,  0.5013,  1.4206,  1.1542],
        [-1.5366, -0.5577, -0.4383,  1.1572]])
tensor([-0.9578,  1.7518,  0.9796,  0.4105])
tensor([0.4105, 1.1178, 1.1542, 1.1572])


8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [24]:
tensor8=torch.randn((3,3))
tensor9=torch.randn((3,))
print(tensor8)
print(tensor9)
tensor10=torch.sub(tensor8, tensor9)
print(tensor10)

tensor([[ 1.1271,  0.1414,  0.8661],
        [ 1.0181, -1.5408,  0.1183],
        [ 1.0806,  0.5506,  0.0448]])
tensor([ 0.9940, -0.4363, -1.5975])
tensor([[ 0.1330,  0.5777,  2.4636],
        [ 0.0241, -1.1045,  1.7158],
        [ 0.0865,  0.9869,  1.6423]])


9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [25]:
tensor11=torch.randn((3,4))
print(tensor11)
res=torch.sum(tensor11)
print(res)

tensor([[ 0.9320, -0.0770,  0.3346, -1.0173],
        [-1.0937, -1.8067, -1.3913, -0.8563],
        [-0.9901, -0.4665,  1.0271, -1.0906]])
tensor(-6.4959)


10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [27]:
tensor12=torch.randn((3,4))
print(tensor12)
print('Mean_Row', torch.mean(tensor12,dim=1))

tensor([[-0.8913, -0.5254, -0.5221, -0.3377],
        [ 1.5381,  1.0848, -0.1155, -0.2734],
        [ 2.8653,  0.5639, -0.0278,  0.2338]])
Mean_Row tensor([-0.5691,  0.5585,  0.9088])
