In [1]:
import numpy as np
import torch

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [2]:
# Set the random seed so things are predictable
torch.manual_seed(42)
# Create random tensor
first = torch.randn((6,5))
print('first random tensor is:\n',first)

second  = torch.randn((1,5)).T
print('second random tensor after transposing is:\n',second)

# Perform matrix multiplication 
mul = first @ second
print('matrix multlipication of first and second tensor is:\n',mul)

first random tensor is:
 tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784],
        [-1.2345, -0.0431, -1.6047, -0.7521,  1.6487],
        [-0.3925, -1.4036, -0.7279, -0.5594, -2.3169],
        [-0.2168, -1.3847, -0.8712, -0.2234,  1.7174],
        [ 0.3189, -0.4245, -0.8286,  0.3309, -1.5576],
        [ 0.9956, -0.8798, -0.6011, -1.2742,  2.1228]])
second random tensor after transposing is:
 tensor([[-0.0915],
        [ 0.2352],
        [ 2.2440],
        [ 0.5817],
        [ 0.4528]])
matrix multlipication of first and second tensor is:
 tensor([[ 1.2771],
        [-3.1890],
        [-3.3020],
        [-1.6132],
        [-2.5010],
        [-1.4270]])


2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [3]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable
# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))
#====================================================================

class Linear: 
    def __init__(self, features ,weights, bias) :
        self.features = features
        self.weights = weights
        self.bias = bias
    
    def linear_operation(self):
        result = torch.matmul(self.features, self.weights.t()) + self.bias
        return result


linear_operator = Linear(features, weights, bias)
result = linear_operator.linear_operation()

print("Generated Features are:\n",features)
print("Weights are:\n",weights)
print("Bias is:\n",bias)
print('========================================')
print("Result of Linear Operation is:\n",result)

Generated Features are:
 tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
Weights are:
 tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
Bias is:
 tensor([[0.3177]])
Result of Linear Operation is:
 tensor([[-1.6619]])


3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [4]:
# Find max
print('max is:',torch.max(mul))
# Find min
print('min is:',torch.min(mul))
# Find arg max
print('argmax is:', torch.argmax(mul))
# Find arg min
print('argmin is:', torch.argmin(mul))

max is: tensor(1.2771)
min is: tensor(-3.3020)
argmax is: tensor(0)
argmin is: tensor(2)


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [5]:
# Initialize the random seed
torch.manual_seed(42)


# Generate a tensor with random values
uniq = torch.randn((1,1,1,25))

# Eliminate singleton dimensions
uniq= uniq.squeeze()

# Display the tensors along with their shapes
uniq.shape

torch.Size([25])

5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [12]:
one_dim_tensor =torch.arange(1,6)
print('1D tensor is:',one_dim_tensor)
print('shape of 1D tensor is:',one_dim_tensor.shape)
print('========================================')

two_dim_tensor = one_dim_tensor.unsqueeze(0)
print('2D tensor is:',two_dim_tensor)
print('shape of 2D tensor is:',two_dim_tensor.shape)

1D tensor is: tensor([1, 2, 3, 4, 5])
shape of 1D tensor is: torch.Size([5])
2D tensor is: tensor([[1, 2, 3, 4, 5]])
shape of 2D tensor is: torch.Size([1, 5])


6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [7]:
torch.manual_seed(42)
first_two_dim_tensor = torch.randn((2,3))
print('first 2D tensor is:\n',first_two_dim_tensor)
print('===============================')

second_two_dim_tensor = torch.randn((2,3))
print('second 2D tensor is:\n', second_two_dim_tensor)
element_wise_add =torch.add ( first_two_dim_tensor, second_two_dim_tensor )
print('================================')
print('elementwise sum is:\n',element_wise_add)

first 2D tensor is:
 tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])
second 2D tensor is:
 tensor([[ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]])
elementwise sum is:
 tensor([[ 2.5449, -0.5092,  0.6961],
        [ 0.4977, -0.5880,  0.6230]])


7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [8]:
torch.manual_seed(42)
two_d = torch.randn((4,4))
print('2D tensor is:\n',two_d)

first_raw = two_d [0 , :]
print('first raw as a tensor:\n',first_raw)
print('=============================================')
last_column = two_d [:,-1]
print('last column as a tensor:\n',last_column)

2D tensor is:
 tensor([[ 1.9269,  1.4873,  0.9007, -2.1055],
        [ 0.6784, -1.2345, -0.0431, -1.6047],
        [-0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -0.7688,  0.7624]])
first raw as a tensor:
 tensor([ 1.9269,  1.4873,  0.9007, -2.1055])
last column as a tensor:
 tensor([-2.1055, -1.6047, -1.4036,  0.7624])


8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [9]:
torch.manual_seed(42)
tensor_2D = torch.randn((3,3))
print('2D tensor is:\n',tensor_2D)
print('\n shape of 2D tensor is:\n',tensor_2D.shape)
print('==================================')
tensor_1D = torch.randn((3))
print('1D tensor is:\n', tensor_1D)
print('\n shape of 1D tensor is:\n',tensor_1D.shape)
print('==================================')
add_tensor =  torch.add(tensor_2D, tensor_1D)
print('their addition is:\n',add_tensor)
print('\n shape of addition tensor is:\n',add_tensor.shape)

2D tensor is:
 tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

 shape of 2D tensor is:
 torch.Size([3, 3])
1D tensor is:
 tensor([0.2674, 0.5349, 0.8094])

 shape of 1D tensor is:
 torch.Size([3])
their addition is:
 tensor([[ 0.6040,  0.6637,  1.0438],
        [ 0.4977, -0.5880,  0.6230],
        [ 2.4756, -0.1031,  1.2710]])

 shape of addition tensor is:
 torch.Size([3, 3])


9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [10]:
torch.manual_seed(42)
two_d_tensor = torch.randn((3,4))
print('2D tensor is:\n', two_d_tensor)
print('=========================================')
sum_of_all = torch.sum(two_d_tensor)
print('sum of all elements is:\n',sum_of_all)

2D tensor is:
 tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
sum of all elements is:
 tensor(3.2646)


10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [11]:
torch.manual_seed(42)
two_d_tensor2 = torch.randn((3,4))
print('2D tensor is:\n', two_d_tensor2)
print('=========================================')
mean_of_raw = torch.mean(two_d_tensor2, dim=1)
print('mean along each raw is:\n',mean_of_raw)

2D tensor is:
 tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
mean along each raw is:
 tensor([0.2326, 0.0653, 0.5183])
