In [1]:
import numpy as np
import torch

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [8]:
# Set the random seed so things are predictable

# Create random tensor

# Perform matrix multiplication 

torch.manual_seed(7)

random_tensor_1 = torch.randn((4,3))
random_tensor_2 = torch.randn((3,4))
multiply = random_tensor_1 @ random_tensor_2
print(multiply)

tensor([[ 3.5812, -0.7450,  1.2882,  0.7087],
        [ 2.3774,  0.8962,  2.9980,  2.5721],
        [ 3.2018,  0.0375,  2.4605,  1.9172],
        [ 0.7798, -0.4621, -1.6297, -1.7187]])


2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [33]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

def linear_func(features, weights, bias):
    return weights.T @ features + bias


linear_func(features, weights, bias) 

tensor([[ 0.4490, -0.3858, -0.5296,  1.3148, -1.1953],
        [ 0.3699,  0.0381, -0.0190,  0.7140, -0.2836],
        [ 0.1368,  1.2865,  1.4845, -1.0556,  2.4014],
        [ 0.2974,  0.4263,  0.4485,  0.1637,  0.5513],
        [ 0.5646, -1.0048, -1.2751,  2.1922, -2.5266]])

3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [41]:
torch.manual_seed(7) 

features = torch.randn((1, 5))

weights = torch.randn_like(features)

bias = torch.randn((1, 1))

def linear_func(features, weights, bias):
    return weights.T @ features + bias

# Find max
print('max :',linear_func(features, weights, bias).max())

# Find min
print('min :',linear_func(features, weights, bias).min())

# Find arg max
print('arg_max :',linear_func(features, weights, bias).argmax())

# Find arg min
print('arg_min :',linear_func(features, weights, bias).argmin())

max : tensor(2.4014)
min : tensor(-2.5266)
arg_max : tensor(14)
arg_min : tensor(24)


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [49]:
# Initialize the random seed
torch.manual_seed(7) 

# Generate a tensor with random values
my_tensor = torch.randn((1,1,1,25))

# Eliminate singleton dimensions
my_vector = my_tensor.reshape(-1)

# Display the tensors along with their shapes
print(my_vector.shape)
print(my_vector)

torch.Size([25])
tensor([-0.8201,  0.3956,  0.8989, -1.3884, -0.1670,  0.2851, -0.6411, -0.8937,
         0.9265, -1.2169, -0.0810,  1.3615, -1.3032,  0.0875, -1.3850,  0.5036,
        -0.0835, -0.5640, -2.0565, -0.3567,  1.0956,  0.4824,  1.3989,  1.4059,
        -1.4013])


5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [69]:
new_vector = torch.arange(1,6)
print(new_vector.shape)

new_tensor = new_vector.reshape(1,5)
print(new_tensor.shape)

torch.Size([5])
torch.Size([1, 5])


6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [70]:
tensor_1 = torch.randn(2,3)
tensor_2 = torch.randn(2,3)

tensor_3 = tensor_1 + tensor_2

7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [71]:
my_tensor = torch.randn(4,4)
print(my_tensor)

first_row = my_tensor[0]
las_col = my_tensor[:,-1]
print(first_row)
print(las_col)

tensor([[-1.0268, -0.0790,  0.1438,  1.4025],
        [-0.4167,  0.1655, -0.7157,  1.2425],
        [-0.7125, -0.6910,  0.2311, -0.7556],
        [-0.1198,  0.9545,  0.1492,  1.6222]])
tensor([-1.0268, -0.0790,  0.1438,  1.4025])
tensor([ 1.4025,  1.2425, -0.7556,  1.6222])


8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [81]:
tensor_1 = torch.randn(3,3)
tensor_2 = torch.tensor([1,1,1]).reshape(3,1)
print(tensor_1)
print(tensor_2)
print(tensor_2.shape)
print(tensor_1 + tensor_2)

tensor([[-0.0147, -0.5648,  0.4987],
        [-1.8017, -0.2172,  0.9465],
        [ 0.7827, -0.7846, -1.9137]])
tensor([[1],
        [1],
        [1]])
torch.Size([3, 1])
tensor([[ 0.9853,  0.4352,  1.4987],
        [-0.8017,  0.7828,  1.9465],
        [ 1.7827,  0.2154, -0.9137]])


9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [82]:
tensor_2d = torch.randn(3,4)

elements_sum = tensor_2d.sum()
elements_sum

tensor(-4.6030)

10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [83]:
tensor_2d = torch.randn(3,4)
print(tensor_2d.mean(dim=1))

tensor([ 0.2408, -0.0782,  1.0269])
