In [1]:
import numpy as np
import torch

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [2]:
# Set the random seed so things are predictable
torch.manual_seed(7)
# Create random tensor
tensor1 = torch.randn((6, 5))
tensor2 = torch.randn((1, 5))
# Perform matrix multiplication 
mult = torch.matmul(tensor1,tensor2.T)
mult

tensor([[ 4.4529],
        [-3.6277],
        [-3.1083],
        [-0.2883],
        [-6.2504],
        [ 3.1558]])

2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [3]:
def simple_lin(features, weights, bias):
    lin = features @ weights.T + bias
    return lin

### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable
# Features are 3 random normal variables
features = torch.randn((6,3))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

lin_f = simple_lin(features, weights, bias)
print(lin_f)

tensor([[-5.1359,  2.3591,  0.3638, -0.2126,  1.7309,  3.5867],
        [-2.1095,  0.8311, -0.0094, -0.1558,  0.6184,  1.4048],
        [ 0.8458, -1.8596, -0.0485, -1.0214, -1.6897, -2.8365],
        [-3.5496,  1.3408,  2.2700, -1.7512, -1.3636, -3.4808],
        [ 4.9268,  0.5534, -0.6683,  1.7400,  0.1392, -0.8780],
        [-0.7444,  0.9947,  1.1376, -0.5359, -0.7481, -2.2731]])


3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [4]:
# Find max
print("max: ", mult.max())
# Find min
print("min: ", mult.min())
# Find arg max
print("arg max: ", mult.argmax())
# Find arg min
print("arg min: ", mult.argmin())

max:  tensor(4.4529)
min:  tensor(-6.2504)
arg max:  tensor(0)
arg min:  tensor(4)


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [5]:
# Initialize the random seed
torch.manual_seed(7)
# Generate a tensor with random values
unique_tensor = torch.randn(1, 1, 1, 25)
# Eliminate singleton dimensions
squeezed_tensor = torch.squeeze(unique_tensor,[0,1,2])
# Display the tensors along with their shapes
print("squeezed tensor: ",squeezed_tensor)
print("size: ",squeezed_tensor.size())

squeezed tensor:  tensor([-0.8201,  0.3956,  0.8989, -1.3884, -0.1670,  0.2851, -0.6411, -0.8937,
         0.9265, -1.2169, -0.0810,  1.3615, -1.3032,  0.0875, -1.3850,  0.5036,
        -0.0835, -0.5640, -2.0565, -0.3567,  1.0956,  0.4824,  1.3989,  1.4059,
        -1.4013])
size:  torch.Size([25])


5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [6]:
t_1d = torch.arange(1,6)
t_2d = t_1d.view(1,5)
t_2d

tensor([[1, 2, 3, 4, 5]])

6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [7]:
t1 = torch.randn(2,3)
t2 = torch.randn(2,3)
addition = t1 + t2
addition

tensor([[ 1.1213, -0.3216,  0.6005],
        [ 0.2026, -1.9230,  1.3880]])

7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [8]:
t1 = torch.randn(4,4)
row_f = t1[0,:]
col_l = t1[:,-1]
print("original: ", t1)
print("first row: ", row_f)
print("last col: ", col_l)

original:  tensor([[ 0.1825, -0.5146,  0.8005, -1.2432],
        [-1.7178, -0.5824, -0.6153,  1.5496],
        [ 1.1970,  0.4675, -0.1439, -0.8120],
        [-0.3866, -1.0370,  0.5920, -0.7557]])
first row:  tensor([ 0.1825, -0.5146,  0.8005, -1.2432])
last col:  tensor([-1.2432,  1.5496, -0.8120, -0.7557])


8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [9]:
t_1d = torch.randn(3,)
t_2d = torch.randn(3,3)
mult_t = t_2d + t_1d
print("1d tensor: ", t_1d)
print("2d tensor: ", t_2d)
print("mult: ", mult_t)

1d tensor:  tensor([-0.0672, -0.8564,  0.6569])
2d tensor:  tensor([[ 0.0413, -1.3750,  0.1321],
        [ 0.1583, -0.7080,  0.3778],
        [ 0.2359,  0.8545,  0.6220]])
mult:  tensor([[-2.5901e-02, -2.2313e+00,  7.8908e-01],
        [ 9.1041e-02, -1.5643e+00,  1.0347e+00],
        [ 1.6872e-01, -1.8724e-03,  1.2789e+00]])


9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [10]:
t2 = torch.randn(3,4)
print("original: ", t2)
print("sum: ", t2.sum())

original:  tensor([[-1.5603,  0.2040,  0.7279, -1.0332],
        [ 2.6176,  1.8689,  1.1457,  1.0762],
        [-0.9065,  1.4684,  0.6288, -0.7817]])
sum:  tensor(5.4559)


10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [11]:
t2 = torch.randn(3,4)
print("original: ", t2)
print("mean of each row: ", t2.mean(dim=1))

original:  tensor([[-1.4498, -0.8319,  0.5037,  0.6949],
        [ 0.4883,  0.4031, -1.1259,  0.9992],
        [ 0.5922,  1.6515,  0.2860,  0.3323]])
mean of each row:  tensor([-0.2708,  0.1912,  0.7155])
