In [1]:
import numpy as np
import torch

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [2]:
# Set the random seed so things are predictable
torch.manual_seed(0)
# Create random tensor
tensor1 =  torch.rand(6, 5)
tensor2 =  torch.rand(1, 5)
# Perform matrix multiplication
mm = torch.mm(tensor1, tensor2.T)

In [3]:
mm

tensor([[0.9649],
        [1.0261],
        [0.5746],
        [1.0351],
        [1.4298],
        [1.1693]])

2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [31]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable
# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))
y = features * weights + bias

In [22]:
features.shape

torch.Size([1, 5])

In [23]:
def model(w, x, b):
    return w * x + b

In [24]:
def criterion(y_pred, y_true):
    return torch.power(y_pred - y_true, 2).mean()

In [33]:
y_pred = model(weights, features, bias)

In [34]:
y_pred

tensor([[ 0.4490,  0.0381,  1.4845,  0.1637, -2.5266]])

3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [35]:
# Find max
print("max : ", y_pred.max())
# Find min
print("max : ", y_pred.min())
# Find arg max
print("max : ", y_pred.argmax())
# Find arg min
print("max : ", y_pred.argmax())

max :  tensor(1.4845)
max :  tensor(-2.5266)
max :  tensor(2)
max :  tensor(2)


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [11]:
# Initialize the random seed
torch.manual_seed(7)

# Generate a tensor with random values
tensor4 = torch.Tensor(1, 1, 1, 25)
# Eliminate singleton dimensions
tensor4_squeezed = torch.squeeze(tensor4)
# Display the tensors along with their shapes
print("tensor4 shape : ", tensor4.shape)
print("tensor4_squeezed shape : ", tensor4_squeezed.shape)

tensor4 shape :  torch.Size([1, 1, 1, 25])
tensor4_squeezed shape :  torch.Size([25])


5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [12]:
tensor5 = torch.range(1, 5)
tensor5_reshape = tensor5.reshape(1, 5)

print("tensor5 : ", tensor5)
print("tensor5_reshape : ", tensor5_reshape)
print("tensor5_reshape : ", tensor5_reshape.shape)


tensor5 :  tensor([1., 2., 3., 4., 5.])
tensor5_reshape :  tensor([[1., 2., 3., 4., 5.]])
tensor5_reshape :  torch.Size([1, 5])


<ipython-input-12-f35ff555ef5e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor5 = torch.range(1, 5)


6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [13]:
# Initialize the random seed
torch.manual_seed(7)
tensor6 = torch.randint(10, (2, 3))
tensor6_add = 2 +  tensor6

In [14]:
print("tensor6 : ", tensor6)
print("added tensor6 : ", tensor6_add)

tensor6 :  tensor([[5, 2, 1],
        [6, 3, 7]])
added tensor6 :  tensor([[7, 4, 3],
        [8, 5, 9]])


7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [15]:
torch.manual_seed(7)
tensor7 = torch.randint(10, (4, 4))
print(tensor7.shape)
print(tensor7)

torch.Size([4, 4])
tensor([[5, 2, 1, 6],
        [3, 7, 7, 9],
        [8, 1, 8, 1],
        [8, 7, 2, 0]])


In [16]:
last_col_tensor7 = tensor7[:, -1]
first_row_tensor7 = tensor7[0, :]
print('first_row_tensor7 : ', first_row_tensor7)
print('last_col_tensor7 : ', last_col_tensor7)

first_row_tensor7 :  tensor([5, 2, 1, 6])
last_col_tensor7 :  tensor([6, 9, 1, 0])


8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [17]:
torch.manual_seed(7)
tensor8_2D = torch.randint(10, (3, 3))
tensor8_1D = torch.randint(10, (3,))
broadcast_tensor8 = torch.add(tensor8_2D, tensor8_1D)
print('broadcast_tensor8 : ', broadcast_tensor8)

broadcast_tensor8 :  tensor([[ 6, 10,  2],
        [ 7, 11,  8],
        [ 8, 17,  9]])


9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [18]:
torch.manual_seed(7)
tensor9 = torch.randint(10, (3, 4))
print("tensor9 : ", tensor9)
print("sum_tensor9 : ", tensor9.sum())

tensor9 :  tensor([[5, 2, 1, 6],
        [3, 7, 7, 9],
        [8, 1, 8, 1]])
sum_tensor9 :  tensor(58)


10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [19]:
torch.manual_seed(7)
tensor10 = torch.randint(10, (3, 4))
tensor10 = tensor10.float()
mean_row_tensor10 = torch.mean(tensor10, 1)

print("tensor10 : ", tensor10)

print("mean_row_tensor10 : ", mean_row_tensor10)


tensor10 :  tensor([[5., 2., 1., 6.],
        [3., 7., 7., 9.],
        [8., 1., 8., 1.]])
mean_row_tensor10 :  tensor([3.5000, 6.5000, 4.5000])
