In [1]:
import numpy as np
import torch

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [2]:
# Set the random seed so things are predictable
torch.manual_seed(42)

# Create random tensor
tensor1_1 = torch.rand((6, 5))
tensor1_2 = torch.rand((1, 5))

# Perform matrix multiplication 
matrix_multiplication = tensor1_1 @ tensor1_2.T
print(matrix_multiplication)

tensor([[1.9389],
        [1.8879],
        [2.2856],
        [1.3511],
        [1.0735],
        [0.7813]])


2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [3]:
class LinearModel:
    def __init__(self, features: torch.Tensor, weights: torch.Tensor, bias: torch.Tensor) -> None:
        self.features = features
        self.weights = weights
        self.bias = bias

    def predict(self) -> float:
        return self.features @ self.weights.T + self.bias
    

### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

linear_model = LinearModel(features, weights, bias)
print(linear_model.predict())

tensor([[-1.6619]])


3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [4]:
# Find max
max = matrix_multiplication.max()
print("max: ", max)

# Find min
min = matrix_multiplication.min()
print("min: ", min)

# Find arg max
max_index = matrix_multiplication.argmax()
print("max_index: ", max_index)

# Find arg min
min_index = matrix_multiplication.argmin()
print("min_index: ", min_index)

max:  tensor(2.2856)
min:  tensor(0.7813)
max_index:  tensor(2)
min_index:  tensor(5)


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [5]:
# Initialize the random seed
torch.manual_seed(42)

# Generate a tensor with random values
tensor4 = torch.rand((1, 1, 1, 25))

# Eliminate singleton dimensions
squeezed_tensor = tensor4.squeeze()

# Display the tensors along with their shapes
print("squeezed tensor: ", squeezed_tensor)
print("squeezed tensor shape: ",squeezed_tensor.shape)

squeezed tensor:  tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739,
        0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053])
squeezed tensor shape:  torch.Size([25])


5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [6]:
tensor5 = torch.arange(1, 6)
reshaped_tensor = tensor5.reshape(1, 5)
print("reshaped tensor: ", reshaped_tensor)
print("reshaped tensor shape: ", reshaped_tensor.shape)

reshaped tensor:  tensor([[1, 2, 3, 4, 5]])
reshaped tensor shape:  torch.Size([1, 5])


6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [7]:
torch.manual_seed(42)

tensor6_1 = torch.rand((2, 3))
tensor6_2 = torch.rand((2, 3))
matrix_summation = tensor6_1 + tensor6_2
print(matrix_summation)

tensor([[1.1388, 1.7086, 1.3236],
        [1.0925, 1.3250, 1.1945]])


7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [8]:
torch.manual_seed(42)

tensor7 = torch.rand((4, 4))
first_row_vector = tensor7[0]
last_column_vector = tensor7[:, -1]

print(tensor7)
print(first_row_vector)
print(last_column_vector)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])
tensor([0.8823, 0.9150, 0.3829, 0.9593])
tensor([0.9593, 0.7936, 0.5936, 0.4294])


8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [9]:
torch.manual_seed(42)

tensor8_1 = torch.rand((3, 3))
tensor8_2 = torch.rand((3))

print(tensor8_1)
print(tensor8_2)
print(tensor8_1 + tensor8_2)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([0.1332, 0.9346, 0.5936])
tensor([[1.0155, 1.8496, 0.9764],
        [1.0925, 1.3250, 1.1945],
        [0.3898, 1.7282, 1.5344]])


9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [10]:
torch.manual_seed(42)

tensor9 = torch.rand((3, 4))

print(tensor9)
print(tensor9.sum())

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor(7.7831)


10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [11]:
torch.manual_seed(42)

tensor10 = torch.rand((3, 4))

print(tensor10)
print(tensor10.mean(dim=1))

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([0.7849, 0.5104, 0.6505])
