In [1]:
import numpy as np
import torch

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [2]:
# Set the random seed so things are predictable
torch.random.manual_seed(42)
# Create random tensor
matrix1=torch.randn(6,5)
matrix2=torch.randn(1,5)
# Perform matrix multiplication 
matrix_multi=torch.mm(matrix1, matrix2.t())  

print(f"Tensor 1: \n {matrix1}\n")
print(f"Tensor 2: \n {matrix2}\n")
print(f"Matrix Multiplication: \n {matrix_multi}")

Tensor 1: 
 tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784],
        [-1.2345, -0.0431, -1.6047, -0.7521,  1.6487],
        [-0.3925, -1.4036, -0.7279, -0.5594, -2.3169],
        [-0.2168, -1.3847, -0.8712, -0.2234,  1.7174],
        [ 0.3189, -0.4245, -0.8286,  0.3309, -1.5576],
        [ 0.9956, -0.8798, -0.6011, -1.2742,  2.1228]])

Tensor 2: 
 tensor([[-0.0915,  0.2352,  2.2440,  0.5817,  0.4528]])

Matrix Multiplication: 
 tensor([[ 1.2771],
        [-3.1890],
        [-3.3020],
        [-1.6132],
        [-2.5010],
        [-1.4270]])


2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [3]:
def multiplies(features,weight,bias):
    return torch.mm(features,weight.t())+ bias
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

result=multiplies(features,weights,bias)
print(result)

tensor([[-1.6619]])


3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [6]:
# Find max
print(f"MAX: {torch.max(matrix_multi)}")
# Find min
print(f"MIN: {torch.min(matrix_multi)}")
# Find arg max
print(f"ARG MAX: {torch.argmax(matrix_multi)}")
# Find arg min
print(f"ARG MIN: {torch.argmin(matrix_multi)}")

MAX: 1.2770949602127075
MIN: -3.3019661903381348
ARG MAX: 0
ARG MIN: 2


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).


In [8]:
# Initialize the random seed
torch.random.manual_seed(42)
# Generate a tensor with random values
first_tensor=torch.randn(1,1,25)
# Eliminate singleton dimensions
reshape_tensor=torch.squeeze(first_tensor)
# Display the tensors along with their shapes
print(f"First Tensor Shape: {first_tensor.shape}\n")
print(f"First Tensor :\n {first_tensor}\n")
print(f"Reshape Tensor Shape: {reshape_tensor.shape}\n")
print(f"Reshape Tensor :\n {reshape_tensor}")

First Tensor Shape: torch.Size([1, 1, 25])

First Tensor :
 tensor([[[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431,
          -1.6047, -0.7521, -0.6866, -0.4934,  0.2415, -1.1109,  0.0915,
          -2.3169, -0.2168, -1.3847, -0.3957,  0.8034, -0.6216, -0.5920,
          -0.0631, -0.8286,  0.3309, -1.5576]]])

Reshape Tensor Shape: torch.Size([25])

Reshape Tensor :
 tensor([ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431, -1.6047,
        -0.7521, -0.6866, -0.4934,  0.2415, -1.1109,  0.0915, -2.3169, -0.2168,
        -1.3847, -0.3957,  0.8034, -0.6216, -0.5920, -0.0631, -0.8286,  0.3309,
        -1.5576])


5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)


In [9]:
first_tensor=torch.arange(1,6)
reshape_tensor=first_tensor.view(1,5)
print(f"First Tensor:\n {first_tensor}")
print(f"Reshape Tensor:\n {reshape_tensor}")

First Tensor:
 tensor([1, 2, 3, 4, 5])
Reshape Tensor:
 tensor([[1, 2, 3, 4, 5]])


6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [10]:
torch.random.manual_seed(42)
tensor1=torch.randn(2,3)
tensor2=torch.randn(2,3)
result=tensor1+tensor2
print(f"Tensor1:\n {tensor1}\n")
print(f"Tensor2:\n {tensor2}\n")
print(f"Result:\n {result}\n")

Tensor1:
 tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])

Tensor2:
 tensor([[ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]])

Result:
 tensor([[ 2.5449, -0.5092,  0.6961],
        [ 0.4977, -0.5880,  0.6230]])



7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [11]:
torch.random.manual_seed(42)
first_tensor=torch.randn(4,4)
first_row=first_tensor[0, :]
last_column=first_tensor[:, -1]
print(f"First Tensor:\n {first_tensor}\n")
print(f"First Row:\n {first_row}\n")
print(f"Last Column:\n {last_column}\n")

First Tensor:
 tensor([[ 1.9269,  1.4873,  0.9007, -2.1055],
        [ 0.6784, -1.2345, -0.0431, -1.6047],
        [-0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -0.7688,  0.7624]])

First Row:
 tensor([ 1.9269,  1.4873,  0.9007, -2.1055])

Last Column:
 tensor([-2.1055, -1.6047, -1.4036,  0.7624])



8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [12]:
torch.random.manual_seed(42)
tensor_2d = torch.randn(3,3)
tensor_1d = torch.randn(3)
result=tensor_2d+tensor_1d
print(f"Tensor 2D:\n {tensor_2d}\n")
print(f"Tensor_1D:\n {tensor_1d}\n")
print(f"Result:\n {result}\n")

Tensor 2D:
 tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

Tensor_1D:
 tensor([0.2674, 0.5349, 0.8094])

Result:
 tensor([[ 0.6040,  0.6637,  1.0438],
        [ 0.4977, -0.5880,  0.6230],
        [ 2.4756, -0.1031,  1.2710]])



9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [13]:
torch.random.manual_seed(42)
tensor_2d = torch.randn(3,4)
sum_tensor=torch.sum(tensor_2d)
print(f"Tensor 2D:\n {tensor_2d}\n")
print(f"Sum Tensor:\n {sum_tensor}\n")

Tensor 2D:
 tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])

Sum Tensor:
 3.264584541320801



10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [15]:
torch.random.manual_seed(42)
tensor_2d = torch.randn(3,4)
mean_row=torch.mean(tensor_2d,dim=1)
print(f"Tensor 2D:\n {tensor_2d}\n")
print(f"Mean Row:\n {mean_row}\n")

Tensor 2D:
 tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])

Mean Row:
 tensor([0.2326, 0.0653, 0.5183])

