In [1]:
import numpy as np
import torch

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [13]:
# Set the random seed so things are predictable
torch.manual_seed(7)
# Create random tensor
tensor1=torch.randn(6,5)
tensor2=torch.randn(1,5)
# Perform matrix multiplication 
multi=tensor1*tensor2
print(multi)

tensor([[ 0.6138,  0.7859, -0.2608,  3.3627, -0.0487],
        [-0.2134, -1.2734,  0.2593, -2.2441, -0.1561],
        [ 0.8680, -0.9140, -0.2056, -2.4529, -0.4037],
        [-0.3769, -0.1659,  0.0068, -0.4223,  0.6700],
        [-0.7163, -1.3147, -0.4059, -3.4050, -0.4085],
        [-0.9710,  3.2594,  0.3066,  0.6336, -0.0729]])


2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [14]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

def multiple_mat(features,weight,bias):
    result=features*weight + bias
    return(result)

multiple_mat(features=features,weight=weights,bias=bias)

tensor([[ 0.4490,  0.0381,  1.4845,  0.1637, -2.5266]])

3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [15]:
# Find max
print(torch.max(multi))
# Find min
print(torch.min(multi))
# Find arg max
print(torch.argmax(multi))
# Find arg min
print(torch.argmin(multi))

tensor(3.3627)
tensor(-3.4050)
tensor(3)
tensor(23)


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [19]:
# Initialize the random seed
torch.manual_seed(7)
# Generate a tensor with random values
unsqueeze=torch.randn(1,1,1,25)
# Eliminate singleton dimensions
squeeze=unsqueeze.view(25)
# Display the tensors along with their shapes
print(unsqueeze.shape)
print(squeeze.shape)

torch.Size([1, 1, 1, 25])
torch.Size([25])


5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [27]:
torch.arange(1,6).reshape(1,5)

tensor([[1, 2, 3, 4, 5]])

6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [28]:
two_d_1=torch.randn(2,3)
two_d_2=torch.randn(2,3)
two_d_1+two_d_2

tensor([[ 1.1213, -0.3216,  0.6005],
        [ 0.2026, -1.9230,  1.3880]])

7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [33]:
example7=torch.randn(4,4)
first_row=example7[1]
last_column=example7[:,-1]
print(example7)
print(first_row)
print(last_column)

tensor([[ 0.1333,  0.5600, -0.7351, -0.2240],
        [-0.7955, -2.1339, -0.7493,  0.6340],
        [-1.5414, -0.3315,  0.5505,  0.1268],
        [-1.5152, -0.9127,  1.2716,  0.1451]])
tensor([-0.7955, -2.1339, -0.7493,  0.6340])
tensor([-0.2240,  0.6340,  0.1268,  0.1451])


8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [38]:
example_8_2d=torch.randn(3,3)
example_8_1d=torch.randn(3,)
print(example_8_1d)
print(example_8_2d)
print(example_8_2d+example_8_1d)

tensor([-0.0718,  0.4710, -0.4351])
tensor([[-1.0906, -1.9475,  0.1032],
        [ 0.9534, -1.1759, -1.1693],
        [-0.7851, -0.0601, -1.5256]])
tensor([[-1.1624, -1.4766, -0.3319],
        [ 0.8815, -0.7049, -1.6044],
        [-0.8570,  0.4109, -1.9607]])


9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [44]:
torch.manual_seed(42)
example_9=torch.randn(3,4)
print(example_9)
print(example_9.sum())

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
tensor(3.2646)


10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [45]:
torch.manual_seed(42)
example_10=torch.randn(3,4)
print(example_10)
print(example_10.mean(dim=1))
print([p.mean() for p in example_10])

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
tensor([0.2326, 0.0653, 0.5183])
[tensor(0.2326), tensor(0.0653), tensor(0.5183)]
