In [46]:
import numpy as np
import torch

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [132]:
# Set the random seed so things are predictable
np.random.seed(42)
# Create random tensor
tensor1 = torch.tensor(np.random.randn(30).reshape(6,5))
tensor2 = torch.tensor(np.random.randn(5).reshape(1,5))
print(f"tensors with shapes (6, 5) \n {tensor1} \n tensors with shapes (1, 5)\n {tensor2}\n ")
# Perform matrix multiplication 
print(f"matrix multiplication \n {tensor1 * tensor2}")


tensors with shapes (6, 5) 
 tensor([[ 0.4967, -0.1383,  0.6477,  1.5230, -0.2342],
        [-0.2341,  1.5792,  0.7674, -0.4695,  0.5426],
        [-0.4634, -0.4657,  0.2420, -1.9133, -1.7249],
        [-0.5623, -1.0128,  0.3142, -0.9080, -1.4123],
        [ 1.4656, -0.2258,  0.0675, -1.4247, -0.5444],
        [ 0.1109, -1.1510,  0.3757, -0.6006, -0.2917]], dtype=torch.float64) 
 tensors with shapes (1, 5)
 tensor([[-0.6017,  1.8523, -0.0135, -1.0577,  0.8225]], dtype=torch.float64)
 
matrix multiplication 
 tensor([[-2.9888e-01, -2.5610e-01, -8.7420e-03, -1.6109e+00, -1.9260e-01],
        [ 1.4088e-01,  2.9251e+00, -1.0358e-02,  4.9657e-01,  4.4628e-01],
        [ 2.7884e-01, -8.6266e-01, -3.2658e-03,  2.0237e+00, -1.4188e+00],
        [ 3.3833e-01, -1.8760e+00, -4.2415e-03,  9.6043e-01, -1.1617e+00],
        [-8.8189e-01, -4.1820e-01, -9.1144e-04,  1.5070e+00, -4.4778e-01],
        [-6.6743e-02, -2.1320e+00, -5.0709e-03,  6.3530e-01, -2.3993e-01]],
       dtype=torch.float64)


2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [48]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

def multiplies_tensor(features,weights,bias):
    y = features*weights+bias
    print("y = β0 + β1X1 + β2X2 + ... \n",f"bias = {bias}  weight vector = {weights}")
    return (f"final tensor = {y}")

print(multiplies_tensor(features,weights,bias))

y = β0 + β1X1 + β2X2 + ... 
 bias = tensor([[0.3177]])  weight vector = tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
final tensor = tensor([[ 0.4490,  0.0381,  1.4845,  0.1637, -2.5266]])


3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [49]:
# Find max
# Find arg max
print(torch.max(tensor1,dim=0))
print(torch.max(tensor2,dim=0))
# Find min
# Find arg min
print(torch.min(tensor1,dim=0))
print(torch.min(tensor2,dim=0))

# print(torch.argmax(tensor1,dim=0))
# print(torch.argmax(tensor2,dim=0))
# print(torch.argmin(tensor1,dim=0))
# print(torch.argmin(tensor2,dim=0))

torch.return_types.max(
values=tensor([1.4656, 1.5792, 0.7674, 1.5230, 0.5426], dtype=torch.float64),
indices=tensor([4, 1, 1, 0, 1]))
torch.return_types.max(
values=tensor([-0.6017,  1.8523, -0.0135, -1.0577,  0.8225], dtype=torch.float64),
indices=tensor([0, 0, 0, 0, 0]))
torch.return_types.min(
values=tensor([-0.5623, -1.1510,  0.0675, -1.9133, -1.7249], dtype=torch.float64),
indices=tensor([3, 5, 4, 2, 2]))
torch.return_types.min(
values=tensor([-0.6017,  1.8523, -0.0135, -1.0577,  0.8225], dtype=torch.float64),
indices=tensor([0, 0, 0, 0, 0]))


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [104]:
# Initialize the random seed
np.random.seed(42)
# Generate a tensor with random values
random_tensor = torch.tensor(np.random.randn(25).reshape(1,1,1,25))
unique_tensor = torch.unique(random_tensor,dim=3)
print('unique tensor with dimensions (1, 1, 1, 25) \n',unique_tensor)
# Eliminate singleton dimensions
singleton_dimensions_tensor = unique_tensor.squeeze()
# Display the tensors along with their shapes
print('tensor with shape (25) \n',singleton_dimensions_tensor.shape,'\n',singleton_dimensions_tensor)

unique tensor with dimensions (1, 1, 1, 25) 
 tensor([[[[-1.9133, -1.7249, -1.4247, -1.4123, -1.0128, -0.9080, -0.5623,
           -0.5444, -0.4695, -0.4657, -0.4634, -0.2342, -0.2341, -0.2258,
           -0.1383,  0.0675,  0.2420,  0.3142,  0.4967,  0.5426,  0.6477,
            0.7674,  1.4656,  1.5230,  1.5792]]]], dtype=torch.float64)
tensor with shape (25) 
 torch.Size([25]) 
 tensor([-1.9133, -1.7249, -1.4247, -1.4123, -1.0128, -0.9080, -0.5623, -0.5444,
        -0.4695, -0.4657, -0.4634, -0.2342, -0.2341, -0.2258, -0.1383,  0.0675,
         0.2420,  0.3142,  0.4967,  0.5426,  0.6477,  0.7674,  1.4656,  1.5230,
         1.5792], dtype=torch.float64)


5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [115]:
onedim_tensor = torch.tensor(range(1,6))
twodim_tensor = onedim_tensor.unsqueeze(-2)
print(twodim_tensor.shape)

torch.Size([1, 5])


6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [112]:
np.random.seed(42)
first = torch.tensor(np.random.randint(1,100,6).reshape(2,3))
secend = torch.tensor(np.random.randint(1,100,6).reshape(2,3))
print('first tensor \n',first,'\n secend tensor \n',secend,'\n first + secend \n', first + secend)

first tensor 
 tensor([[52, 93, 15],
        [72, 61, 21]]) 
 secend tensor 
 tensor([[83, 87, 75],
        [75, 88, 24]]) 
 first + secend 
 tensor([[135, 180,  90],
        [147, 149,  45]])


7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [141]:
np.random.seed(42)
secend_twodim_tensor = torch.tensor(np.random.randn(16).reshape(4,4))
first_row = secend_twodim_tensor[0,:]
last_column = secend_twodim_tensor[:,-1].reshape(-1,1)
print(f'first row\n {first_row} \n last column \n{last_column}')

first row
 tensor([ 0.4967, -0.1383,  0.6477,  1.5230], dtype=torch.float64) 
 last column 
tensor([[ 1.5230],
        [ 0.7674],
        [-0.4657],
        [-0.5623]], dtype=torch.float64)


8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [154]:
np.random.seed(42)
third_twodim_tensor = torch.tensor(np.random.randn(9).reshape(3,3))
secend_onedim_tensor = torch.tensor(np.random.randint(1,10,3))
torch.add(third_twodim_tensor,secend_onedim_tensor)

tensor([[5.4967, 0.8617, 6.6477],
        [6.5230, 0.7658, 5.7659],
        [6.5792, 1.7674, 5.5305]], dtype=torch.float64)

9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [156]:
np.random.seed(42)
fourth_twodim_tensor = torch.tensor(np.random.randn(12).reshape(3,4))
print(fourth_twodim_tensor)
print(fourth_twodim_tensor.sum())

tensor([[ 0.4967, -0.1383,  0.6477,  1.5230],
        [-0.2342, -0.2341,  1.5792,  0.7674],
        [-0.4695,  0.5426, -0.4634, -0.4657]], dtype=torch.float64)
tensor(3.5515, dtype=torch.float64)


10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [161]:
print(fourth_twodim_tensor.mean(dim=0))

tensor([-0.0690,  0.0567,  0.5878,  0.6082], dtype=torch.float64)
