In [2]:
import numpy as np
import torch


1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [4]:
# Set the random seed so things are predictable
torch.manual_seed(42)

# Create random tensor
tensor1 = torch.rand(6,5)
tensor2 = torch.rand(1,5)
print(tensor1.shape)
print(tensor2.shape)
# Perform matrix multiplication 
torch.mm(tensor1, tensor2.T)


torch.Size([6, 5])
torch.Size([1, 5])


tensor([[1.9389],
        [1.8879],
        [2.2856],
        [1.3511],
        [1.0735],
        [0.7813]])

2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [5]:
def linear_operation(features, weights, bias):
    return torch.mm(features, weights.t()) + bias

### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

linear_operation(features, weights, bias)

tensor([[-1.6619]])

3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [6]:
# Find max
tensor1.max()

# Find min
tensor1.min()

# Find arg max
tensor1.argmax()
# Find arg min
tensor1.argmin()

tensor(29)

4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [7]:
# Initialize the random seed
torch.manual_seed(42)
# Generate a tensor with random values
tensor3 = torch.rand(1,1,1,25)
# Eliminate singleton dimensions
tensor3.flatten()
# Display the tensors along with their shapes

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739,
        0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053])

5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [8]:
tensor_1d = torch.tensor([1, 2, 3, 4, 5])

tensor_2d = tensor_1d.view(1, 5)

6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [29]:
tensor_2d = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])

tensor2_2d = torch.tensor([[7, 8, 9],
                        [10, 11, 12]])

result_tensor = tensor1 + tensor2

result_tensor

tensor([[1.8338, 0.9903, 1.2689, 1.5425, 0.7281],
        [1.5524, 0.3318, 1.6797, 1.5240, 0.4708],
        [1.8862, 0.6688, 1.7554, 1.1509, 1.0787],
        [1.3810, 0.9607, 1.4599, 0.8498, 0.9651],
        [1.2212, 0.5166, 1.1829, 1.4149, 0.4430],
        [1.2210, 0.4341, 1.0854, 1.1304, 0.3438]])

7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [31]:
random_tensor = torch.rand(4, 4)
first_row = random_tensor[0, :]
last_column = random_tensor[:, -1]

print (random_tensor)
print(first_row)
last_column


tensor([[0.3644, 0.7104, 0.9464, 0.7890],
        [0.2814, 0.7886, 0.5895, 0.7539],
        [0.1952, 0.0050, 0.3068, 0.1165],
        [0.9103, 0.6440, 0.7071, 0.6581]])
tensor([0.3644, 0.7104, 0.9464, 0.7890])


tensor([0.7890, 0.7539, 0.1165, 0.6581])

8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [11]:
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

tensor_1d = torch.tensor([10, 20, 30])
result_tensor = tensor_2d + tensor_1d.unsqueeze(1)
print(tensor_2d)
print(tensor_1d)
result_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([10, 20, 30])


tensor([[10],
        [20],
        [30]])

9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [35]:
random_tensor = torch.rand(3, 4)
print(random_tensor)
torch.sum(random_tensor)

tensor([[0.4913, 0.8913, 0.1447, 0.5315],
        [0.1587, 0.6542, 0.3278, 0.6532],
        [0.3958, 0.9147, 0.2036, 0.2018]])


tensor(5.5687)

10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [36]:
random_tensor = torch.rand(3, 4)
print(random_tensor)
torch.mean(random_tensor, dim=1)

tensor([[0.2018, 0.9497, 0.6666, 0.9811],
        [0.0874, 0.0041, 0.1088, 0.1637],
        [0.7025, 0.6790, 0.9155, 0.2418]])


tensor([0.6998, 0.0910, 0.6347])