In [116]:
import numpy as np
import torch
%config IPCompleter.use_jedi=False

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [117]:
# Set the random seed so things are predictable
torch.manual_seed(42)

# Create random tensor
tensor1 = torch.randint(low=0 ,high=30,size=(6,5))
tensor2 = torch.randint(low=0 ,high=30,size=(1,5))

# Perform matrix multiplication 
multiplication = tensor1 * tensor2

tensor1 & tensor2

tensor([[12,  0, 16,  0,  6],
        [ 4,  0,  8,  2, 23],
        [12,  0, 16, 16, 21],
        [ 4,  0, 25, 19, 16],
        [ 0,  0,  9,  3, 21],
        [12,  0,  9,  3, 19]])

2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [118]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

class MyTensor:
    def __init__(self,features, weights, bias,*args, **kwargs):
        self.features=features
        self.weights=weights
        self.bias=bias

    def calc(self):
        return self,weights * self.features + self.bias

tensi = MyTensor(features, weights, bias)
tensi.calc()

(<__main__.MyTensor at 0x7efeb62fc150>,
 tensor([[ 0.4490,  0.0381,  1.4845,  0.1637, -2.5266]]))

3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [119]:
# Find max
print(f"{multiplication.max()= }")
# Find min
print(f"{multiplication.min()= }")
# Find arg max
print(f"{multiplication.argmax()= }")
# Find arg min
print(f"{multiplication.argmin()= }")


multiplication.max()= tensor(667)
multiplication.min()= tensor(0)
multiplication.argmax()= tensor(24)
multiplication.argmin()= tensor(1)


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [120]:
# Initialize the random seed
torch.manual_seed(19)
# Generate a tensor with random values
tensor4 = torch.torch.randint(1,50,(1,1,1,25))
# Eliminate singleton dimensions
tensor4.reshape(25)
# Display the tensors along with their shapes

tensor([49, 29,  6, 17,  9, 49, 16, 33, 44, 47,  2, 49, 36, 21, 13,  5,  6, 11,
        45, 43,  2, 36, 33, 31, 20])

5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [121]:
tensor5 = torch.randint(1,50,(5,))
tensor5.reshape(1,5)

tensor([[15, 45, 27, 15, 43]])

6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [122]:
tensor6 = torch.randint(1,50,(2,3))
tensor6_ = torch.randint(1,50,(2,3))
tensor6 + tensor6_

tensor([[77, 15, 21],
        [56, 44, 41]])

7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [123]:
torch.manual_seed(19)
tensor7 = torch.randint(1,50,(4,4))
tensor7_first_row = tensor7[0]
tensor7_last_col = tensor7[-1]
tensor7, tensor7_first_row , tensor7_last_col 

(tensor([[49, 29,  6, 17],
         [ 9, 49, 16, 33],
         [44, 47,  2, 49],
         [36, 21, 13,  5]]),
 tensor([49, 29,  6, 17]),
 tensor([36, 21, 13,  5]))

8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [124]:
torch.manual_seed(19)
tensor8 = torch.randint(1,50,(3,3))
tensor8_ = torch.randint(1,50,(3,))
tensor8 + tensor8_

tensor([[96, 31, 55],
        [64, 11, 98],
        [63, 35, 93]])

9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [125]:
torch.manual_seed(19)
tensor9 = torch.randint(1,50,(3,4))

tensor9, tensor9.sum()

(tensor([[49, 29,  6, 17],
         [ 9, 49, 16, 33],
         [44, 47,  2, 49]]),
 tensor(350))

10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [126]:
torch.manual_seed(19)
tensor10 = torch.rand((3,4))

tensor10, tensor10.mean(dim=0), tensor10.mean(dim=1) # dim 1 is Answer

(tensor([[0.9686, 0.1999, 0.8799, 0.6622],
         [0.2161, 0.1192, 0.3617, 0.0167],
         [0.8503, 0.9620, 0.2479, 0.2946]]),
 tensor([0.6783, 0.4270, 0.4965, 0.3245]),
 tensor([0.6776, 0.1784, 0.5887]))