In [2]:
import numpy as np
import torch

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [10]:
# Set the random seed so things are predictable
torch.manual_seed(0)
# Create random tensor
a = torch.rand(6, 5)
b = torch.rand(1, 5)
# Perform matrix multiplication 
mul_mat = torch.matmul(a, b.T)
print("Answer:", "\n", mul_mat)

Answer: 
 tensor([[0.9649],
        [1.0261],
        [0.5746],
        [1.0351],
        [1.4298],
        [1.1693]])


2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [8]:
### Generate some data
# Set the random seed so things are predictable
torch.manual_seed(0)
# Features are 3 random normal variables
features = randint2d = torch.randn(10,3) 
# True weights for our data, random normal variables again
weights = torch.randn(features.shape[1],1)
# and a true bias term
bias = torch.randn((1, 1))

### Returns the result of the linear operation
def linear_model(inputs, w, b):
    return torch.matmul(features, w) + b

print("Outputs:", "\n", linear_model(features, weights, bias))

Outputs: 
 tensor([[ 7.5478e-01],
        [-1.1194e+00],
        [-4.2790e-01],
        [-2.1230e-03],
        [-5.1449e-01],
        [-3.7118e-01],
        [-7.0034e-01],
        [ 2.4119e+00],
        [-1.2817e-01],
        [-3.4301e+00]])


3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [13]:
# Find max
Minimum = mul_mat.min()
# Find min
Maximum = mul_mat.max()
# Find arg max
Maximum_Index= mul_mat.argmax()
# Find arg min
Minimum_Index = mul_mat.argmin()
print("\n", "min_value:", Minimum, "\n", "min_index:", Minimum_Index, "\n", "max_value:", Maximum, "\n", "amx_index:", Maximum_Index)


 min_value: tensor(0.5746) 
 min_index: tensor(2) 
 max_value: tensor(1.4298) 
 amx_index: tensor(4)


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [27]:
# Initialize the random seed
torch.manual_seed(0)
# Generate a tensor with random values
c = torch.rand(1, 1 , 1, 25)
# Eliminate singleton dimensions
c_reshape = c.reshape(25)
# Display the tensors along with their shapes
print(" basic_form:", c.size(), "\n", "reshape_form:",c_reshape.size())

 basic_form: torch.Size([1, 1, 1, 25]) 
 reshape_form: torch.Size([25])


5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [28]:
d= torch.arange(1,6)
d_reshape = d.reshape(1,5)
print(" basic_form:", d.size(), "\n", "reshape_form:", d_reshape.size())

 basic_form: torch.Size([5]) 
 reshape_form: torch.Size([1, 5])


6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [29]:
e = torch.rand(2,3)
f = torch.rand(2,3)
sum_e_f = torch.add(e,f)
print(" sum of e and f tensors:", "\n", sum_e_f)

 sum of e and f tensors: 
 tensor([[1.4849, 1.1286, 0.3060],
        [0.3359, 0.4051, 0.5132]])


7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [33]:
g = torch.rand(4, 4)
g_first_row = g[0,]
g_last_col = g[:,-1]
print("matrix:", "\n", g, "\n", "first row:", "\n", g_first_row, "\n", "last column:", "\n", g_last_col)

matrix: 
 tensor([[0.4158, 0.4177, 0.2711, 0.6923],
        [0.2038, 0.6833, 0.7529, 0.8579],
        [0.6870, 0.0051, 0.1757, 0.7497],
        [0.6047, 0.1100, 0.2121, 0.9704]]) 
 first row: 
 tensor([0.4158, 0.4177, 0.2711, 0.6923]) 
 last column: 
 tensor([0.6923, 0.8579, 0.7497, 0.9704])


8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [40]:
h = torch.rand(3, 3)
i = torch.rand(3)
sum_h_i = torch.add(h, i)
print("sum:", "\n", sum_h_i, "\n", sum_h_i.size())

sum: 
 tensor([[0.5111, 0.3293, 0.4817],
        [0.7929, 1.0715, 1.1740],
        [0.4121, 1.1092, 0.5124]]) 
 torch.Size([3, 3])


9. Create a 2D tensor of shape (3, 4) filled with random values and compute the sum of all elements.

In [43]:
j = torch.rand(3, 4)
print("matrix:", j, "\n", "sum of elements:", torch.sum(j))

matrix: tensor([[0.6766, 0.3798, 0.3948, 0.0880],
        [0.7709, 0.8970, 0.8421, 0.1473],
        [0.5223, 0.1475, 0.2248, 0.2086]]) 
 sum of elements: tensor(5.2997)


10. Create a 2D tensor of shape (3, 4) filled with random values and compute the mean along each row.

In [46]:
print("mean along each row:", "\n", torch.mean(j, 0))

mean along each row: 
 tensor([0.6566, 0.4748, 0.4872, 0.1480])
